# Assignment 0

### <span style="color:chocolate"> Submission requirements </span>

Your work will not be graded if your notebook doesn't include output. In other words, <span style="color:red"> make sure to rerun your notebook before submitting to Gradescope </span> (Note: if you are using Google Colab: go to Edit > Notebook Settings  and uncheck Omit code cell output when saving this notebook, otherwise the output is not printed).

Additional points may be deducted if these requirements are not met:

    
* Comment your code;
* Each graph should have a title, labels for each axis, and (if needed) a legend. Each graph should be understandable on its own;
* Try and minimize the use of the global namespace (meaning, keep things inside functions).
---

### Import libraries

In [1]:
import numpy as np
np.random.seed(seed=1)

---
### <span style="color:chocolate">Exercise 1:</span> Homogenous data types (10 points)

1. Create a numpy array (my_array1) containing only integer values. Print the shape of the array and the type of its elements;
2. Create another numpy array (my_array2) containing a mix of integer and string values. Print the shape of the array and the type of its elements. What explains the datatype of the array?

In [5]:
my_array1 = np.array ([1,2,3,4,5])
print("my_array1 shape:", my_array1.shape)
print("my_array1 type:", my_array1.dtype)

my_array2 = np.array([1,2,3,"four",5])
print("my_array2 shape:", my_array2.shape)
print("my_array2 type:", my_array2.dtype)

my_array1 shape: (5,)
my_array1 type: int64
my_array2 shape: (5,)
my_array2 type: <U21


---
#### <span style="color:chocolate">Exercise 2:</span> The size attribute (10 points)

Create a numpy array (my_array3) and print its shape, size, and data type. What does size represent?

In [7]:
my_array3 = np.array([[1,2,3],[4,5,6]])
print("my_array3 shape:", my_array3.shape)
print("my_array3 size:", my_array3.size)
print("my_array3 type:", my_array3.dtype)

my_array3 shape: (2, 3)
my_array3 size: 6
my_array3 type: int64


---
#### <span style="color:chocolate">Exercise 3:</span> Tabular data layout (10 points)

Create a tabular data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:
* the first input is num_samples, and
* the second input is num_features. 

Print the shape of the array.

In [9]:
# already defined first and second inputs
num_samples = 100
num_features = 17

data= np.random.random((num_samples, num_features))
print("data shape:", data.shape)

data shape: (100, 17)


---
#### <span style="color:chocolate">Exercise 4:</span> Image data layout (10 points)

Create an image data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:

* the first input is num_images;
* the second input is num_rows;
* the third input is num_cols;
* the fourth input is num_channels.

Print the shape of the array.

In [11]:
# already defined inputs
num_images = 100
num_rows = 256
num_cols = 256
num_channels = 3 #(RGB)

images = np.random.random((num_images, num_rows, num_cols,num_channels))
print(images.shape)

(100, 256, 256, 3)


---
#### <span style="color:chocolate">Exercise 5: </span>Mathematical operations on numpy arrays (15 points)

Create a (3, 2) numpy array (you can name it my_array4) containing only integer values. Perform the following tasks:

1. Print the shape of the array;
2. Print the sum of all elements (hint: the axis argument is set to None);
3. Print the sum of all elements by column;
3. Print the sum of all elements by row and change the type of the resulting array elements to float;
5. Print the first row of the array;
6. Print the second row of the array;
7. Select the element at position (1, 0);
8. Modify the element at position (2, 1) by setting its value to 10 and print the array again;
9. Loop over all the elements in the array. Print the output.

In [15]:
my_array4 = np.array([[1,2],[3,4],[5,6]], dtype = int)
print("1.Shape of the array:", my_array4.shape)
print("2.Sum of all elements:", my_array4.sum(axis=None))
print("3.Sum of all elements by column:", my_array4.sum(axis=0))
print("4.Sum of all elements by row (float):", my_array4.sum(axis=1).astype(float))
print("5.First row of the array:", my_array4[0])
print("6.Second row of the array:", my_array4[1])
print("7.Element at position (1,0):", my_array4[1, 0])
my_array4[2,1] = 10
print("8.The array after set element of position (2,1) to 10", my_array4)
print("9. Looping over all elements:")
for element in my_array4.flat:
    print(element)

1.Shape of the array: (3, 2)
2.Sum of all elements: 21
3.Sum of all elements by column: [ 9 12]
4.Sum of all elements by row (float): [ 3.  7. 11.]
5.First row of the array: [1 2]
6.Second row of the array: [3 4]
7.Element at position (1,0): 3
8.The array after set element of position (2,1) to 10 [[ 1  2]
 [ 3  4]
 [ 5 10]]
9. Looping over all elements:
1
2
3
4
5
10


You can find more examples here: https://numpy.org/doc/stable/reference/routines.math.html

---
#### <span style="color:chocolate">Exercise 6:</span> Create arrays (15 points)

1. Create and print a (3,2) numpy array of pixel values between 0 and 1.
2. Create and print a (27,) numpy array representing years from 1991 to 2017
3. Create and print a (3, 5, 10) numpy array of zeros
4. Create and print a (3, 5, 10) numpy array of ones
5. Create and print an array with a constant value (let's say 5) using np.ones()
6. Create and print an array with random numbers drawn from a normal distribution with mean 0 and standard deviation 1. Set the sample size to 10.


In [27]:
np.random.seed(42)
np.set_printoptions(edgeitems=3, infstr='inf', linewidth=75, nanstr='nan', 
                    precision=8, suppress=False, threshold=1000, sign='-')

my_array61 = np.random.rand(3,2)
print("1. (3,2) pixel values array:\n", my_array61)
my_array62 = np.arange(1991, 2018)
print("2. (27,) years array:", my_array62)
my_array63 = np.zeros((3,5,10))
print("3. (3, 5, 10) zeros array:\n", my_array63)
my_array64 = np.ones((3, 5, 10))
print("4. (3, 5, 10) ones array:\n", my_array64)
my_array65 = np.ones((2,3)) * 5
print("5. Constant value array:\n", my_array65)
my_array66 = np.random.normal(loc=0.0, scale=1.0, size = 10)
print("6. Normal distribution array (size 10):\n", my_array66)

1. (3,2) pixel values array:
 [[0.37454012 0.95071431]
 [0.73199394 0.59865848]
 [0.15601864 0.15599452]]
2. (27,) years array: [1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
3. (3, 5, 10) zeros array:
 [[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
4. (3, 5, 10) ones array:
 [[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 

---
#### <span style="color:chocolate">Exercise 7:</span> Reshape arrays (10 points)

Consider the following array:

In [29]:
years = np.arange(1991, 2018, 1)
print(years.shape)

(27,)


Perform the following operations on this array:
    
1. Create 3 nested arrays, each of size (3, 3). Call this array years_3d (Hint: use np.reshape());
2. Convert the years_3d array to a flat 1D array. Call this array years_1d (Hint: use np.flatten());
3. Add a new dimension (axis=0) to the years_1d array. Call this array years_2d (Hint: use np.expand_dims());
4. Remove the first axis from years_2d array. Call this array years_1d (Hint: use np.squeeze()).

For each exercise print the array and its shape.

In [31]:
years_3d = np.reshape(years, (3,3,3))
print("1. years_3d array:", years_3d)
print("shape:", years_3d.shape)
years_1d = years_3d.flatten()
print("2. years_1d array:", years_1d)
print("shape:", years_1d.shape)
years_2d = np.expand_dims(years_1d, axis = 0)
print("3. years_2d array:", years_2d)
print("shape:", years_2d.shape)
years_1d_squeezed = np.squeeze(years_2d, axis=0)
print("4. Squeezed years_1d:", years_1d_squeezed)
print("shape:", years_1d_squeezed.shape)


1. years_3d array: [[[1991 1992 1993]
  [1994 1995 1996]
  [1997 1998 1999]]

 [[2000 2001 2002]
  [2003 2004 2005]
  [2006 2007 2008]]

 [[2009 2010 2011]
  [2012 2013 2014]
  [2015 2016 2017]]]
shape: (3, 3, 3)
2. years_1d array: [1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
shape: (27,)
3. years_2d array: [[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
  2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]]
shape: (1, 27)
4. Squeezed years_1d: [1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
shape: (27,)


---
#### <span style="color:chocolate">Exercise 8:</span> Joining arrays (10 points)

Provide 8 examples that use the methods <span style="color:cornflowerBlue">np.concatenate()</span> and <span style="color:cornflowerBlue">np.stack()</span>. Note: create 4 examples using each method.

In [37]:
a1 = np.array([1,2,3])
b1 = np.array([4,5,6])
concatenate_1 = np.concatenate((a1,b1))
print("Concatenate example 1:", concatenate_1)
print("shape:", concatenate_1.shape)

a2 = np.array([[1,2],[3,4]])
b2 = np.array([[5,6],[7,8]])
concatenate_2 = np.concatenate((a2,b2), axis = 0)
print("Concatenate example 2:", concatenate_2)
print("shape:", concatenate_2.shape)
concatenate_3 = np.concatenate((a2,b2), axis = 1)
print("Concatenate example 3:", concatenate_3)
print("shape:", concatenate_3.shape)

a3 = np.ones((2,2,1))
b3 = np.zeros((2,2,2))
concatenate_4 = np.concatenate((a3,b3), axis = 2)
print("Concatenate example 4:", concatenate_4)
print("shape:", concatenate_4.shape)

stack_1 = np.stack((a1,b1), axis = 0)
print("Stack example 1:", stack_1)
print("shape:", stack_1.shape)

stack_2 = np.stack((a1,b1), axis = 1)
print("Stack example 2:", stack_2)
print("shape:", stack_2.shape)

stack_3 = np.stack((a2,b2), axis = 0)
print("Stack example 3:", stack_3)
print("shape:", stack_3.shape)

a4 = np.ones((2,2)) * 255
b4 = np.ones((2,2)) * 120
c4 = np.ones((2,2)) * 0
stack_4 = np.stack((a4,b4,c4), axis = -1)
print("Stack example 4:", stack_4)
print("shape:", stack_4.shape)

Concatenate example 1: [1 2 3 4 5 6]
shape: (6,)
Concatenate example 2: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
shape: (4, 2)
Concatenate example 3: [[1 2 5 6]
 [3 4 7 8]]
shape: (2, 4)
Concatenate example 4: [[[1. 0. 0.]
  [1. 0. 0.]]

 [[1. 0. 0.]
  [1. 0. 0.]]]
shape: (2, 2, 3)
Stack example 1: [[1 2 3]
 [4 5 6]]
shape: (2, 3)
Stack example 2: [[1 4]
 [2 5]
 [3 6]]
shape: (3, 2)
Stack example 3: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape: (2, 2, 2)
Stack example 4: [[[255. 120.   0.]
  [255. 120.   0.]]

 [[255. 120.   0.]
  [255. 120.   0.]]]
shape: (2, 2, 3)


---
#### <span style="color:chocolate">Numpy broadcasting</span> 

The term broadcasting describes how NumPy treats arrays during arithmetic operations. You can find more here:  https://numpy.org/doc/stable/user/basics.broadcasting.html

In [38]:
# multiplying an array with a scalar
years = np.arange(1991, 2018, 1)
years * 1

array([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017])

In [39]:
# adding a scalar
years + 2

array([1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019])

In [40]:
# many arithmetic operations are applied element wise on a pair of arrays
a = np.arange(3)
print('Array a:', a)
b = np.arange(3)
print('Array b:', b)
print('Sum of a and b:', a+b)

Array a: [0 1 2]
Array b: [0 1 2]
Sum of a and b: [0 2 4]


In [41]:
# another example
a = np.ones((3, 3))
print('Array a:', a)
b = np.arange(3)
print('\nArray b:', b)
print('\nSum of a and b:', a+b)

Array a: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array b: [0 1 2]

Sum of a and b: [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


---
#### <span style="color:chocolate">Exercise 9:</span> Numpy array standardization (10 points)

Consider the following (10, 4) array:

In [42]:
my_array = np.random.random((10, 4))
print('my_array shape: ', my_array.shape)
my_array

my_array shape:  (10, 4)


array([[0.61185289, 0.13949386, 0.29214465, 0.36636184],
       [0.45606998, 0.78517596, 0.19967378, 0.51423444],
       [0.59241457, 0.04645041, 0.60754485, 0.17052412],
       [0.06505159, 0.94888554, 0.96563203, 0.80839735],
       [0.30461377, 0.09767211, 0.68423303, 0.44015249],
       [0.12203823, 0.49517691, 0.03438852, 0.9093204 ],
       [0.25877998, 0.66252228, 0.31171108, 0.52006802],
       [0.54671028, 0.18485446, 0.96958463, 0.77513282],
       [0.93949894, 0.89482735, 0.59789998, 0.92187424],
       [0.0884925 , 0.19598286, 0.04522729, 0.32533033]])

Peform the following operations on this array:
1. Compute and print the mean and std for each column (note: set keepdims=True for proper broadcasting).
2. Standardize and print the array and its shape using the mean and std you computed above.

In [48]:
column_means = my_array.mean(axis=0, keepdims=True)
column_stds = my_array.std(axis=0, keepdims=True)
print(f"1.Column means: {column_means}\n shape: {column_means.shape}")
print(f"Column stds: {column_stds}\n shape: {column_stds.shape}")

standardized_array = (my_array - column_means)/column_stds
print(f"2.Standardized array: {standardized_array}\n shape: {standardized_array.shape}")

1.Column means: [[0.39855227 0.44510417 0.47080398 0.57513961]]
 shape: (1, 4)
Column stds: [[0.26704731 0.33530526 0.32807859 0.24919441]]
 shape: (1, 4)
2.Standardized array: [[ 0.79873721 -0.91143906 -0.54456261 -0.83781079]
 [ 0.21538397  1.01421547 -0.82641845 -0.24440824]
 [ 0.72594739 -1.18892784  0.41679302 -1.62369408]
 [-1.24884496  1.50245587  1.50826071  0.93604726]
 [-0.35176728 -1.03616644  0.65054243 -0.54169399]
 [-1.03544965  0.14933477 -1.33021622  1.34104453]
 [-0.523399    0.64841842 -0.48492316 -0.22099848]
 [ 0.55480059 -0.77615757  1.52030842  0.80255901]
 [ 2.02565858  1.34123506  0.38739497  1.3914222 ]
 [-1.16106684 -0.74296869 -1.29717911 -1.00246742]]
 shape: (10, 4)


----
#### <span style="color:chocolate">Additional practice question</span> (not graded)

Consider the following image:

In [ ]:
my_image = np.arange(0, 1, 0.04).reshape(5,5)
print(my_image)
my_image.shape

Perform the following operations on this image (do not overwrite the original image):

1. Crop by using a border of size 1;
2. Crop by removing:
    * the first and the last two rows, and
    * the first and the last two columns;
3. Reverse the column order;
4. set to 0.5 elements divizible by 2.